# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  unit-test:
    # TODO: make sure Docker image is actually up to date?
    docker:
      - image: humancompatibleai/evaluating_rewards:latest

    working_directory: /evaluating-rewards

    parallelism: 4

    steps:
      - checkout

      # Download and cache dependencies
      # Note you will need to manually update the Docker image if any binary
      # (non-Python) dependencies change.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          # MUJOCO_KEY is defined in a CircleCI context
          # Do some sanity checks to make sure key works
          command: |
            pip install -r requirements.txt
            pip install pytest-circleci-parallelized
            curl -o /root/.mujoco/mjkey.txt ${MUJOCO_KEY}
            md5sum /root/.mujoco/mjkey.txt
            python -c "import mujoco_py"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # TODO: test coverage
      # TODO: linting
      # TODO: test output
      - run:
          name: run tests
          command: pytest -n 2 --circleci-parallelize -vv tests/

      - store_artifacts:
          path: /tmp/test-reports
          destination: test-reports
      - store_test_results:
          path: /tmp/test-reports
          unit-test:

workflows:
  version: 2
  test:
    jobs:
      - unit-test:
          context: MuJoCo