# Copyright 2019 Adam Gleave
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0

executors:
  my-executor:
    docker:
      - image: humancompatibleai/evaluating_rewards:base
    working_directory: /evaluating-rewards
    environment:
      # If you change these, also change scripts/code_checks.sh
      SRC_FILES: src/ tests/ setup.py
      TYPECHECK_FILES: src/  # tests often do weird things with types, exclude
      NUM_CPUS: 2  # more CPUs visible but we're throttled to 2, which breaks auto-detect

commands:
  dependencies:
    # You must still manually update the Docker image if any
    # binary (non-Python) dependencies change.
    description: "Check out and update Python dependencies."
    steps:
      - checkout
      # Download and cache dependencies
      # Note you will still need to manually update the Docker image if any
      # binary (non-Python) dependencies change.
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: install dependencies
          # MUJOCO_KEY is defined in a CircleCI context
          # Do some sanity checks to make sure key works
          command: |
            curl -o /root/.mujoco/mjkey.txt ${MUJOCO_KEY}
            md5sum /root/.mujoco/mjkey.txt
            [[ -d /venv ]] || /evaluating-rewards/scripts/build_venv.sh /venv
            python -c "import mujoco_py"

      - save_cache:
          paths:
            - /venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: install evaluating_rewards
          # Build a wheel then install to avoid copying whole directory (pip issue #2195)
          command: |
            python setup.py sdist bdist_wheel
            pip install --upgrade dist/evaluating_rewards-*.whl

jobs:
  lintandtype:
    executor: my-executor

    steps:
      - dependencies
      - run:
          name: flake8
          command: flake8 ${SRC_FILES}

      - run:
          name: black
          command: black --check ${SRC_FILES}

      - run:
          name: codespell
          command: codespell -I .codespell.skip --skip='*.pyc,*.pdf,*.png.*.pkl,*.json' ${SRC_FILES}

      - run:
          name: pylint
          command: pylint --extension-pkg-whitelist=numpy -j ${NUM_CPUS} ${SRC_FILES}

      - run:
          name: pytype
          command: pytype -j ${NUM_CPUS} ${TYPECHECK_FILES}

  unit-test:
    executor: my-executor
    parallelism: 4
    steps:
      - dependencies

      - run:
          name: run tests
          command: |
            pytest --cov=/venv/lib/python3.7/site-packages/evaluating_rewards --cov=tests \
                   --junitxml=/tmp/test-reports/junit.xml --no-success-flaky-report \
                   --shard-id=${CIRCLE_NODE_INDEX} --num-shards=${CIRCLE_NODE_TOTAL} \
                   --nb-test-files -n ${NUM_CPUS} -vv tests/ examples/
            mv .coverage .coverage.eval
            coverage combine  # rewrite paths from virtualenv to src/
      - codecov/upload

      - store_artifacts:
          path: /tmp/test-reports
          destination: test-reports
      - store_test_results:
          path: /tmp/test-reports
          unit-test:

workflows:
  version: 2
  test:
    jobs:
      - lintandtype:
          context: MuJoCo
      - unit-test:
          context: MuJoCo
